### ISSUE TITLE
为啥这样子设置 运行不起来，

### ISSUE THREAD

**Issue by wanghaisheng** [Ciyfly/thread_worker#1]
from thread_worker import LimitWorker

def run(keywords, modeno, browser, outfile, notefile):
    # browser = browser.new_tab()

    logger.info("☞等待搜索关键词", "#ffff99")

    logger.info(f"start to do  keyword={keywords}")

# limit_time 是limit_time 秒内有 consumer_count个消费者
w = LimitWorker(run, consumer_count=1, block=False, limit_time=1)

for keyword in klist:
    modeno = 2
    modetext = modes[int(modeno)]
    outfile = Recorder(f"data/{keyword}_{modetext}_1688.xlsx", cache_size=500)
    notefile = Recorder(f"data/{keyword}-{modetext}-notefile.txt")
    w.put([keyword, modeno, browser, outfile, notefile])
    # w.put(iid)
# 这里通过 is_end 方法来阻塞程序
while not w.is_end():
    time.sleep(3)

**Comment by wanghaisheng** [comment]
![image](https://github.com/Ciyfly/thread_worker/assets/2363295/7b2c1140-a2cd-40ef-b7e5-556196e67e8a)

**Comment by wanghaisheng** [comment]
worker is ok

**Comment by Ciyfly** [comment]
非常感谢你的使用和bug修改

**Comment by wanghaisheng** [comment]
this is my second chance to address a bug in AI-powered programming

@Ciyfly  thank 🧒
